# Generated by Django 3.1.4 on 2020-12-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Ingrédient',
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('GR', 'Grammes'), ('CL', 'Centilitre'), ('UN', 'Unité'), ('PI', 'Pincée')], max_length=50, verbose_name='Unité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
            options={
                'verbose_name': 'Ingrédient',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('season', models.CharField(blank=True, choices=[('SP', 'Printemps'), ('SU', 'Été'), ('AU', 'Automne'), ('WI', 'Hiver')], max_length=50, verbose_name='Saison')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('difficulty', models.IntegerField(choices=[(1, 'Facile'), (2, 'Normal'), (3, 'Difficile'), (4, 'Expert')], verbose_name='Difficulté')),
                ('ingredients', models.ManyToManyField(through='meals.IngredientQuantity', to='meals.Ingredient')),
            ],
            options={
                'verbose_name': 'Repas',
                'verbose_name_plural': 'Repas',
            },
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
