# Generated by Django 3.1.4 on 2020-12-07 21:06

from django.db import migrations, models
import django.db.models.deletion


def create_four_seasons(apps, schemaeditor):
    class Seasons(models.TextChoices):
        spring = "SP", "Printemps"
        summer = "SU", "Été"
        autumn = "AU", "Automne"
        winter = "WI", "Hiver"

    Season = apps.get_model('meals', 'Season')
    for value, text in Seasons.choices:
        Season.objects.create(name=value)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Ingrédient',
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('GR', 'Grammes'), ('CL', 'Centilitre'), ('UN', 'Unité'), ('PI', 'Pincée'), ('SL', 'Tranche')], max_length=50, verbose_name='Unité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
            options={
                'verbose_name': 'Ingrédient',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SP', 'Printemps'), ('SU', 'Été'), ('AU', 'Automne'), ('WI', 'Hiver')], max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('difficulty', models.IntegerField(choices=[(1, 'Facile'), (2, 'Normal'), (3, 'Difficile'), (4, 'Expert')], verbose_name='Difficulté')),
                ('ingredients', models.ManyToManyField(through='meals.IngredientQuantity', to='meals.Ingredient')),
                ('seasons', models.ManyToManyField(blank=True, to='meals.Season', verbose_name='Saisons')),
            ],
            options={
                'verbose_name': 'Repas',
                'verbose_name_plural': 'Repas',
            },
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
        migrations.RunPython(create_four_seasons, reverse_code=migrations.RunPython.noop),
    ]
